export const SHARE = {
	accesError: "Nu ai permisiunea pentru aceasta comanda.",
	connectedError: "Jucatorul nu este conectat/logat.",
	disabledCommandError: "Comanda este momentan dezactivata."
};

export const COLORS = {
	COLOR_SERVER: 'e6255f',
	COLOR_ADMINCHAT: 'e09041',
	COLOR_HELPERCHAT: '9e5c1b'
};

export const INTERACT_TYPES = {

	TYPE_DRIVING_INTERACT: 1
}

/* --- EVENTS --- */
export const RAGE_CLIENT_EVENTS = {

	SHOW_CLIENT_LOGIN: "[RAGEMP]::SHOW_CLIENT_LOGIN::[RAGEMP]",
	HIDE_CLIENT_LOGIN: "[RAGEMP]::HIDE_CLIENT_LOGIN::[RAGEMP]",
	SET_CLIENT_CHECKPOINT: "[RAGEMP]::SET_CLIENT_CHECKPOINT::[RAGEMP]",
	DESTROY_CLIENT_CHECKPOINT: "[RAGEMP]::DESTROY_CLIENT_CHECKPOINT::[RAGEMP]",
	FREEZE_CLIENT:"[RAGEMP]::FREEZE_CLIENT::[RAGEMP]",
	START_CLIENT_FLYMODE: "[RAGEMP]::START_CLIENT_FLYMODE::[RAGEMP]",
	ENABLE_CLIENT_VEHICLE_COLLISION: "[RAGEMP]::ENABLE_CLIENT_VEHICLE_COLLISION::[RAGEMP]",
	DISABLE_CLIENT_VEHICLE_COLLISION: "[RAGEMP]::DISABLE_CLIENT_VEHICLE_COLLISION::[RAGEMP]",
	SET_CLIENT_ENGINE_STATE: "[RAGEMP]::SET_CLIENT_ENGINE_STATE::[RAGEMP]",
	REMOVE_CLIENT_HELMET: "[RAGEMP]::REMOVE_CLIENT_HELMET::[RAGEMP]",
	REMOVE_CLIENT_BELT: "[RAGEMP]::REMOVE_CLIENT_BELT::[RAGEMP]",
	SET_CLIENT_HELMET: "[RAGEMP]::SET_CLIENT_HELMET::[RAGEMP]",
	SET_CLIENT_BELT: "[RAGEMP]::SET_CLIENT_BELT::[RAGEMP]",
	SET_CLIENT_FISH_ROD: "[RAGEMP]::SET_CLIENT_FISH_ROD::[RAGEMP]",
	SHOW_CLIENT_CHARACTER_CREATOR: "[RAGEMP]::SHOW_CLIENT_CHARACTER_CREATOR::[RAGEMP]",
	SHOW_CLIENT_CHAT: "[RAGEMP]::SHOW_CLIENT_CHAT::[RAGEMP]",
	HIDE_CLIENT_CHAT: "[RAGEMP]::HIDE_CLIENT_CHAT::[RAGEMP]",
	SHOW_CLIENT_DIALOG: "[RAGEMP]::SHOW_CLIENT_DIALOG::[RAGEMP]",
	ON_CLIENT_DIALOG_RESPONSE: "[RAGEMP]::ON_CLIENT_DIALOG_RESPONSE::[RAGEMP]",
	START_CLIENT_DMV: "[RAGEMP]::START_CLIENT_DMV::[RAGEMP]",
	STOP_CLIENT_DMV: "[RAGEMP]::STOP_CLIENT_DMV::[RAGEMP]",
	SHOW_CLIENT_ALERT_INPUT: "[RAGEMP]::SHOW_CLIENT_ALERT_INPUT::[RAGEMP]",
	SHOW_CLIENT_INTERACT: "[RAGEMP]::SHOW_CLIENT_INTERACT::[RAGEMP]",
	SHOW_CLIENT_INTERACT_MENU: "[RAGEMP]::SHOW_CLIENT_INTERACT_MENU::[RAGEMP]",
	START_CLIENT_CAMERA_INTERACT: "[RAGEMP]::START_CLIENT_CAMERA_INTERACT::[RAGEMP]",
	ON_CALL_INTERACT_MENU: "[RAGEMP]::ON_CALL_INTERACT_MENU::[RAGEMP]",
	LOAD_CLIENT_HUD: "[RAGEMP]::LOAD_CLIENT_HUD::[RAGEMP]",
	HIDE_CLIENT_HUD: "[RAGEMP]::HIDE_CLIENT_HUD::[RAGEMP]",
	UPDATE_HUD_ONLINE_PLAYERS: "[RAGEMP]::UPDATE_HUD_ONLINE_PLAYERS::[RAGEMP]",
	UPDATE_CLIENT_HUD_ONLINE: "[RAGEMP]::UPDATE_CLIENT_HUD_ONLINE::[RAGEMP]",
	LOAD_CLIENT_HUD_SAFEZONE: "[RAGEMP]::LOAD_CLIENT_HUD_SAFEZONE::[RAGEMP]",
	SET_HUD_ACTIVE: "[RAGEMP]::SET_HUD_ACTIVE::[RAGEMP]",
	UPDATE_CLIENT_HUD_MONEY: "[RAGEMP]::UPDATE_CLIENT_HUD_MONEY::[RAGEMP]",
	UPDATE_CLIENT_HUD_ID: "[RAGEMP]::UPDATE_CLIENT_HUD_ID::[RAGEMP]",
	UPDATE_CLIENT_HUD_WEAPON: "[RAGEMP]::UPDATE_CLIENT_HUD_WEAPON::[RAGEMP]",
	SHOW_CLIENT_SANCTION: "[RAGEMP]::SHOW_CLIENT_SANCTION::[RAGEMP]",
	SHOW_CLIENT_JOB_MENU: "[RAGEMP]::SHOW_CLIENT_JOB_MENU::[RAGEMP]",
}
export const RAGE_GENERAL_EVENTS = {
	KICK_PLAYER: "[RAGEMP]::KICK_PLAYER::[RAGEMP]",
	REMOVE_PLAYER_VARIABLE_COLLISION: "[RAGEMP]::REMOVE_PLAYER_VARIABLE_COLLISION::[RAGEMP]",
	SET_PLAYER_VARIABLE_COLLISION: "[RAGEMP]::SET_PLAYER_VARIABLE_COLLISION::[RAGEMP]",
	SHOW_PLAYER_MENU: "[RAGEMP]::SHOW_PLAYER_MENU::[RAGEMP]",
	SET_PLAYER_CHECKPOINT_VARIABLE: "[RAGEMP]::SET_PLAYER_CHECKPOINT_VARIABLE::[RAGEMP]",
	SET_PLAYER_VARIABLE_MENU_ACTIVE: "[RAGEMP]::SET_PLAYER_VARIABLE_MENU_ACTIVE::[RAGEMP]",
	SET_PLAYER_VARIABLE_ACTIVE_CHAT: "[RAGEMP]::SET_PLAYER_VARIABLE_ACTIVE_CHAT::[RAGEMP]",
	SAVE_SERVER_CAM_COORDS: "[RAGEMP]::SAVE_SERVER_CAM_COORDS::[RAGEMP]",
	SET_SPAWN_PLAYER: "[RAGEMP]::SET_SPAWN_PLAYER::[RAGEMP]",
	REGISTER_SERVER_ACCOUNT: "[RAGEMP]::REGISTER_SERVER_ACCOUNT::[RAGEMP]",
	LOGIN_SERVER_ACCOUNT: "[RAGEMP]::LOGIN_SERVER_ACCOUNT::[RAGEMP]",
	LOAD_PLAYER_ACCOUNT: "[RAGEMP]::LOAD_PLAYER_ACCOUNT::[RAGEMP]",
	START_VEHICLE_ENGINE: "[RAGEMP]::START_VEHICLE_ENGINE::[RAGEMP]",
	SET_PLAYER_HEL_MET: "[RAGEMP]::SET_PLAYER_HEL_MET::[RAGEMP]",
	REMOVE_PLAYER_HEL_MET: "[RAGEMP]::REMOVE_PLAYER_HEL_MET::[RAGEMP]",
	START_PLAYER_DMV: "[RAGEMP]::START_PLAYER_DMV::[RAGEMP]",
	ENTER_PLAYER_CHECKPOINT_DMV: "[RAGEMP]::ENTER_PLAYER_CHECKPOINT_DMV::[RAGEMP]",
	GET_PLAYER_JOB: "[RAGEMP]::GET_PLAYER_JOB::[RAGEMP]",
	CLICK_JOB_TELEPORT: "[RAGEMP]::CLICK_JOB_TELEPORT::[RAGEMP]",
	CLICK_JOB_FIND: "[RAGEMP]::CLICK_JOB_FIND::[RAGEMP]",
	QUIT_PLAYER_JOB: "[RAGEMP]::QUIT_PLAYER_JOB::[RAGEMP]",
	SELL_PLAYER_FISH: "[RAGEMP]::SELL_PLAYER_FISH::[RAGEMP]",
	BUY_PLAYER_ASSETS_FISH: "[RAGEMP]::BUY_PLAYER_ASSETS_FISH::[RAGEMP]",
	SHOW_PLAYER_FISHERMAN_DIALOG: "[RAGEMP]::SHOW_PLAYER_FISHERMAN_DIALOG::[RAGEMP]",
	ACTION_INPUT_FISHERMAN: "[RAGEMP]::ACTION_INPUT_FISHERMAN::[RAGEMP]",
	SET_PLAYER_BEALT: "[RAGEMP]::SET_PLAYER_BEALT::[RAGEMP]",
	REMOVE_PLAYER_BELT: "[RAGEMP]::REMOVE_PLAYER_BELT::[RAGEMP]",
	SET_AMMO_VARIABLE: "[RAGEMP]::SET_AMMO_VARIABLE::[RAGEMP]",
	SET_PLAYER_HAIR: "[RAGEMP]::SET_PLAYER_HAIR::[RAGEMP]",
	SET_PLAYER_PANTS: "[RAGEMP]::SET_PLAYER_PANTS::[RAGEMP]",
	SET_PLAYER_SHIRT: "[RAGEMP]::SET_PLAYER_SHIRT::[RAGEMP]",
	SET_PLAYER_SHOES: "[RAGEMP]::SET_PLAYER_SHOES::[RAGEMP]",
	SET_PLAYER_MALE_GENDER: "[RAGEMP]::SET_PLAYER_MALE_GENDER::[RAGEMP]",
	SET_PLAYER_FEMALE_GENDER: "[RAGEMP]::SET_PLAYER_FEMALE_GENDER::[RAGEMP]",
	CREATE_PLAYER_CHARACTER: "[RAGEMP]::CREATE_PLAYER_CHARACTER::[RAGEMP]",
};